export const JOIN_PRIVATE_ROOM = 'CHAT:JOIN_PRIVATE_ROOM';
export const JOINED_PRIVATE_ROOM = 'CHAT:JOINED_PRIVATE_ROOM';
export const SEND_MESSAGE = 'CHAT:SEND_MESSAGE'
export const NEW_MESSAGE = 'CHAT:NEW_MESSAGE';
export const ERROR_RESPONSE = 'CHAT:ERROR_RESPONSE';
