export const JOIN_PRIVATE_ROOM = 'CHAT:JOIN_PRIVATE_ROOM';
export const JOINED_PRIVATE_ROOM = 'CHAT:JOINED_PRIVATE_ROOM';
export const TYPING_TEXT = 'CHAT:TYPING_TEXT';
export const SEND_MESSAGE = 'CHAT:SEND_MESSAGE'
export const NEW_MESSAGE = 'CHAT:NEW_MESSAGE';
export const TYPING_NOTIFY = 'CHAT:TYPING_NOTIFY';
export const SET_MESSAGE_STATUS = 'CHAT:SET_MESSAGE_STATUS';
export const GET_MESSAGE_STATUS = 'CHAT:GET_MESSAGE_STATUS';
export const ERROR_RESPONSE = 'CHAT:ERROR_RESPONSE';

